In [1]:
import pandas as pd

#### Series

In [2]:
li = [10,20,30,40,50]

li

[10, 20, 30, 40, 50]

In [3]:
type(li)

list

In [5]:
#if one wants to create a series

ser1 = pd.Series(li)

ser1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
type(ser1)

pandas.core.series.Series

In [9]:
ser2 = pd.Series(['Prakhar', 'Manisha', 'Prabhav', 'Sandeep', 'Kunal'])

ser2

0    Prakhar
1    Manisha
2    Prabhav
3    Sandeep
4      Kunal
dtype: object

In [11]:
type(ser2)

pandas.core.series.Series

In [14]:
#no. of dimensions

ser2.ndim

1

In [17]:
#shape of series

ser2.shape

(5,)

***How to create a DataFrame***

In [20]:
di1 = {'Name': ['Prakhar','Manisha','Prabhav','Kunal','Sandeep'],
       'Age': [30,29,28,25,27],
       'Gender': ['M','F','M','M','M']}

In [21]:
df = pd.DataFrame(di1)

df

      Name  Age Gender
0  Prakhar   30      M
1  Manisha   29      F
2  Prabhav   28      M
3    Kunal   25      M
4  Sandeep   27      M

In [22]:
#one can create it directly without di

df = pd.DataFrame({'Name': ['Prakhar','Manisha','Prabhav','Kunal','Sandeep'],
       'Age': [30,29,28,25,27],
       'Gender': ['M','F','M','M','M']})

df

      Name  Age Gender
0  Prakhar   30      M
1  Manisha   29      F
2  Prabhav   28      M
3    Kunal   25      M
4  Sandeep   27      M

In [25]:
#create a dataframe using array

import numpy as np

arr1 = np.array(['Prakhar','Manisha','Prabhav','Kunal','Sandeep'])
arr2 = np.array([30,29,28,25,27])

df = pd.DataFrame({'Name': arr1,
                  'Age': arr2})

df

      Name  Age
0  Prakhar   30
1  Manisha   29
2  Prabhav   28
3    Kunal   25
4  Sandeep   27